# Generated by Django 6.0.4 on 2026-05-17 14:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0001_initial'),
        ('respuestas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='respuesta',
            unique_together={('estudiante', 'ejercicio')},
        ),
    ]
